builder tests: timeout user security test

diff --git a/test b/test
--- a/test
+++ b/test
@@ -90,18 +90,21 @@ echo "sed -i 's/Welcome/Greetings/' /home/build/.cabal/share/*/server-*/response
 chmod +x .s2i/hooks/pre_run
 echo "  * Testing user security ..."
 $s2i
-if ! docker run --rm -u 1001 test 2>&1 | grep -q " Permission denied"; then
+if ! timeout -s KILL 5 docker run --name test --rm -u 1001 test 2>&1 >build.log; then
+  echo "  * server did not fail"
   echo "  * user security FAILED"
   exit 1
 fi
-
+if ! grep -q " Permission denied" build.log; then
+  echo "  * user security FAILED"
+  exit 1
+fi
 #pre_run hook
 echo "echo Greetings >/tmp/response" >.s2i/hooks/pre_run
 sed -i 's|getDataFileName "response" >>= readFile|readFile "/tmp/response"|' Main.hs
 chmod +x .s2i/hooks/pre_run
 check "pre_run hook" "Greetings"
 rm .s2i/hooks/pre_run
-
 echo "PASSED"
 
 #clear up
